
import React, { createContext, useState, useContext, ReactNode } from 'react';
import type { Language } from '../types';

const translations = {
  cs: {
    app_title: "Fotograf AI",
    nav_studio: "Studio",
    nav_upload: "Import",
    nav_raw: "RAW Konvertor",
    nav_analysis: "Analýza",
    nav_manual: "Úpravy",
    nav_batch: "Hromadně",
    nav_presets: "Presety",
    nav_autopilot: "Autopilot",
    nav_remove_obj: "Retuš",
    nav_crop: "Ořez",
    nav_style: "Styl",
    nav_bg: "Pozadí",
    nav_gen: "Generovat",
    nav_export: "Export",
    nav_history: "Historie",
    nav_social: "Sociální média",
    nav_video: "Video (Veo)",
    nav_youtube: "YouTube Miniatury",
    nav_projects: "Projekty",
    nav_clients: "Klienti",
    nav_ai_gallery: "AI Galerie",
    nav_ai_command: "AI Řídicí centrum",
    
    pipeline_workflow: "Postup",
    pipeline_creative: "Kreativa",
    pipeline_management: "Správa",
    pipeline_step_import: "Import",
    pipeline_step_culling: "Výběr",
    pipeline_step_edit: "Základ",
    pipeline_step_retouch: "Retuš",
    pipeline_step_export: "Export",

    status_draft: "Nový",
    status_editing: "Úpravy",
    status_review: "Ke schválení",
    status_delivered: "Dokončeno",

    crm_projects_title: "Projekty",
    crm_projects_desc: "Kompletní přehled zakázek, statusů a galerie.",
    crm_clients_title: "Klienti",
    crm_clients_desc: "Správa kontaktů a jejich projektů.",
    crm_filter_all: "Vše",
    crm_no_projects: "Zatím žádné projekty.",
    crm_no_clients: "Zatím žádní klienti.",
    crm_project_missing: "Projekt nebyl nalezen.",
    crm_client_missing: "Klient nebyl nalezen.",
    crm_unknown_client: "Neznámý klient",
    crm_project_date: "Datum",
    crm_files: "Soubory",
    crm_projects: "projekty",
    crm_open_project: "Otevřít projekt",
    crm_open_client: "Otevřít klienta",
    crm_new_project: "Nový projekt",
    crm_new_project_desc: "Založte novou zakázku a navázanou pipeline.",
    crm_create_project: "Vytvořit projekt",
    crm_project_name: "Název projektu",
    crm_project_name_placeholder: "např. Svatba Novákovi",
    crm_project_type: "Typ zakázky",
    crm_notes: "Poznámky",
    crm_notes_placeholder: "Doplňte poznámky k zakázce",
    crm_cancel: "Zrušit",
    crm_client: "Klient",
    crm_select_client: "Vyberte klienta",
    crm_new_client_short: "+ Nový klient",
    crm_new_client: "Nový klient",
    crm_new_client_desc: "Vytvořte klienta pro rychlé přiřazení zakázek.",
    crm_create_client: "Vytvořit klienta",
    crm_client_name: "Jméno klienta",
    crm_client_name_placeholder: "např. Jan Novák",
    crm_email: "E-mail",
    crm_phone: "Telefon",
    crm_activity_created: "Projekt vytvořen",
    crm_no_activity: "Zatím žádná aktivita.",
    crm_gallery_settings: "Nastavení galerie",
    crm_gallery_settings_desc: "Vyberte fotky a upravte přístup.",
    crm_publish: "Publikovat",
    crm_unpublish: "Zrušit publikaci",
    crm_selected: "Vybráno",
    crm_select_all: "Vybrat vše",
    crm_clear_selection: "Zrušit výběr",
    crm_select: "Vybrat",
    crm_allow_download: "Povolit stahování",
    crm_upload_to_project: "Nahrát fotky",
    crm_uploading_to: "Nahráváte do projektu",
    crm_open_gallery: "Otevřít galerii",
    crm_tab_info: "Info",
    crm_tab_photos: "Fotky",
    crm_tab_gallery: "Galerie",
    crm_tab_activity: "Aktivita",
    crm_status: "Status",
    crm_no_files: "Zatím žádné fotky.",
    crm_open_in_editor: "Otevřít v editoru",
    crm_gallery_missing: "Galerie nebyla nalezena.",
    crm_gallery_title: "Soukromá galerie pro klienta",
    crm_download_all: "Stáhnout vše",
    crm_gallery_empty: "Galerie je zatím prázdná.",

    dashboard_new_job: "Nová zakázka",
    dashboard_continue: "Pokračovat v úpravách",
    dashboard_recent: "Poslední akce",
    dashboard_no_recent: "Zatím žádná historie.",
    dashboard_quick_autopilot: "Bleskový Autopilot",
    dashboard_quick_culling: "Chytrý výběr",

    ai_gallery_search: "Hledat v galerii...",
    ai_gallery_filter_all: "Vše",
    ai_gallery_filter_generate: "Generované",
    ai_gallery_filter_autopilot: "Autopilot",
    ai_gallery_filter_youtube: "YouTube miniatury",
    ai_gallery_loading: "Načítání galerie...",
    ai_gallery_empty: "Zatím žádné AI výtvory.",
    ai_gallery_download: "Stáhnout",
    ai_gallery_delete: "Smazat",
    ai_gallery_select_project: "Vybrat projekt",
    ai_gallery_add_to_project: "Přidat do projektu",

    template_title: "Vyberte typ zakázky",
    template_desc: "Tímto nastavíte nejlepší AI modely a pipeline pro vaši práci.",
    template_portrait: "Portrét",
    template_portrait_desc: "Důraz na pleť a přirozené barvy.",
    template_event: "Svatba / Event",
    template_event_desc: "Konzistence a emoce ve velkém objemu.",
    template_product: "Produkt",
    template_product_desc: "Maximální detaily a čisté pozadí.",
    template_social: "Sociální sítě",
    template_social_desc: "Rychlé ořezy a poutavé popisy.",
    template_skip: "Přeskočit nastavení",

    credits_remaining: "Kredity",
    credits_low: "Nedostatek kreditů",
    credits_cost: "Cena",
    credits_buy: "Dobít kredity",
    
    store_title: "Obchod s kredity",
    store_desc: "Získejte přístup k prémiovým AI funkcím. Kredity se odečítají pouze za úspěšné generování.",
    store_pack_basic: "Start",
    store_pack_pro: "Tvůrce",
    store_pack_ultra: "Profesionál",
    store_btn_buy: "Koupit",
    store_best_value: "Nejvýhodnější",
    store_success: "Kredity úspěšně připsány!",
    
    onboarding_title: "Vítejte ve Studiu Budoucnosti",
    onboarding_step1_title: "Vše na jednom místě",
    onboarding_step1_desc: "Od RAW konverze po generování YouTube miniatur. Fotograf AI je váš kompletní kreativní tým.",
    onboarding_step2_title: "AI pracuje za vás",
    onboarding_step2_desc: "Použijte 'Autopilot' pro okamžité vylepšení, nebo 'Chytrý výběr' pro vytřídění stovek fotek.",
    onboarding_step3_title: "Ekonomika Kreditů",
    onboarding_step3_desc: "Začínáte s 50 kredity zdarma. Náročné AI funkce (Generování, Veo) spotřebovávají kredity.",
    onboarding_btn_next: "Další",
    onboarding_btn_start: "Začít Tvořit",

    turbo_culling: "Chytrý výběr",
    turbo_culling_desc: "AI analyzuje kvalitu a vybere nejlepší snímky.",
    turbo_run_culling: "Spustit technickou analýzu",
    turbo_best_pick: "AI Favorit",
    turbo_bad_quality: "Pozor: Snížená kvalita",
    turbo_express: "Turbo postup",
    turbo_express_desc: "Jedním klikem: Autopilot + Ořez + Popisky.",
    turbo_express_btn: "Spustit turbo postup",
    
    home_title: "Fotograf AI",
    home_subtitle: "Profesionální workflow pro fotografy. Šetřete čas, tvořte umění a mějte hotovo v mžiku.",
    home_enter: "Vstoupit do studia",
    
    upload_title: "Nahrát fotky",
    upload_drag: "Přetáhněte fotografie sem",
    upload_support: "Podpora JPG, PNG, WEBP a",
    upload_raw: "RAW soubory budou automaticky vyvolány a převedeny.",
    upload_btn: "Vybrat soubory",
    upload_processing: "Zpracovávám soubory...",
    
    editor_no_image: "Žádný vybraný obrázek",
    editor_upload_hint: "Nahrajte nebo vyberte obrázek pro zahájení úprav.",
    editor_analyzing: "Analyzuji...",
    editor_desc: "Popis",
    editor_suggestions: "Návrhy na vylepšení",
    editor_proactive: "Proaktivní návrhy",
    editor_tech: "Technické informace",
    
    tool_autopilot_desc: "AI automaticky vylepší váš obrázek. Zachová strukturu a zaměří se na barvy a světlo.",
    tool_autopilot_btn: "Spustit Autopilot",
    tool_remove_desc: "Popište objekt, který chcete odstranit.",
    tool_remove_placeholder: "např. 'modré auto v pozadí'",
    tool_remove_btn: "Odstranit",
    tool_crop_title: "Chytrý Ořez",
    tool_crop_instr: "Instrukce pro AI (Volitelné)",
    tool_crop_placeholder: "např. 'Ořízni na detail obličeje'",
    tool_crop_format: "Cílový formát",
    tool_crop_btn_only: "Pouze Oříznout",
    tool_crop_btn_export: "Oříznout a exportovat",
    tool_bg_desc: "Popište nové pozadí.",
    tool_bg_placeholder: "např. 'rušná ulice v Tokiu'",
    tool_bg_btn: "Vyměnit pozadí",
    tool_style_desc: "Vyberte obrázek, jehož styl chcete aplikovat.",
    tool_style_select: "Vybrat obrázek stylu",
    tool_style_btn: "Aplikovat styl",

    tool_social_title: "Asistent sociálních sítí",
    tool_social_desc: "AI vytvoří poutavé popisky a hashtagy pro váš Instagram.",
    tool_social_btn: "Generovat texty",
    
    tool_video_title: "Oživení fotky (Veo)",
    tool_video_desc: "Vytvořte z fotky video pomocí AI modelu Veo.",
    tool_video_prompt: "Popište pohyb (např. 'filmový zoom')",
    tool_video_btn: "Generovat Video",

    tool_youtube_title: "YouTube Thumbnail Creator",
    tool_youtube_desc: "Vytvořte virální náhledovku s vysokým kontrastem.",
    tool_youtube_topic: "Téma videa",
    tool_youtube_topic_ph: "např. Recenze iPhone 16",
    tool_youtube_text: "Text na miniatuře",
    tool_youtube_text_ph: "např. ŠOKUJÍCÍ PRAVDA",
    tool_youtube_face: "Použít aktuální fotku jako tvář",
    tool_youtube_btn: "Generovat Miniaturu",
    
    manual_title: "Manuální úpravy",
    manual_reset: "Resetovat",
    manual_crop_active: "Aktivovat manuální ořez",
    manual_brightness: "Jas",
    manual_contrast: "Kontrast",
    manual_saturation: "Sytost",
    manual_vibrance: "Živost",
    manual_shadows: "Stíny",
    manual_highlights: "Světlé tóny",
    manual_clarity: "Zřetelnost",
    manual_sharpness: "Ostrost",
    manual_noise: "Redukce šumu",
    manual_export_settings: "Nastavení Exportu",
    manual_finish: "Dokončit a Exportovat",

    export_title: "Exportovat obrázek",
    export_format: "Formát",
    export_quality: "Kvalita",
    export_size: "Velikost",
    export_original: "Původní",
    export_half: "Poloviční",
    export_download: "Stáhnout obrázek",

    batch_title: "Hromadné zpracování",
    batch_subtitle: "Aplikujte AI vylepšení na více obrázků najednou.",
    batch_select: "Vyberte obrázky",
    batch_selected: "vybráno",
    batch_select_all: "Označit vše",
    batch_deselect_all: "Odznačit vše",
    batch_run: "Spustit Autopilot na",
    batch_processing: "Zpracovávám...",
    batch_error: "Chyba při zpracování",
    batch_complete: "Zpracování dokončeno.",

    gen_title: "Vytvořte cokoliv s AI",
    gen_subtitle: "Popište obrázek a nechte AI tvořit.",
    gen_prompt: "Popis obrázku",
    gen_placeholder: "např. Astronaut na koni na Marsu",
    gen_btn: "Generovat obrázek",
    gen_generating: "Generuji...",
    gen_add: "Přidat do projektu",
    
    raw_title: "RAW Konvertor",
    raw_subtitle: "Hromadná konverze profesionálních RAW souborů.",
    raw_convert: "Konvertovat",
    raw_converting: "Analyzuji a převádím",
    raw_add: "Přidat do Studia",
    raw_convert_more: "Převést další",
    raw_done: "Konverze dokončena",
    raw_drag: "Přetáhněte RAW soubory sem",
    raw_or_click: "or click",
    raw_select_other: "Vybrat jiné",
    raw_no_files: "Nebyly vybrány žádné soubory.",
    
    msg_api_missing: "Nastala chyba v komunikaci s AI.",
    msg_success: "Akce dokončena.",
    msg_error: "Došlo k chybě.",
    notify_upload_success: "souborů nahráno.",
    notify_gen_success: "Obrázek vygenerován.",
    notify_raw_success: "souborů připraveno.",

    compare_before: "Před",
    compare_after: "Po",
    compare_btn: "Porovnat",
    export_btn: "Stáhnout"
  },
  en: {
    app_title: "Fotograf AI",
    nav_studio: "Dashboard",
    nav_upload: "Import",
    nav_raw: "RAW Converter",
    nav_analysis: "Analysis",
    nav_manual: "Edits",
    nav_batch: "Batch",
    nav_presets: "Presets",
    nav_autopilot: "Autopilot",
    nav_remove_obj: "Retouch",
    nav_crop: "Auto Crop",
    nav_style: "Style Transfer",
    nav_bg: "Background",
    nav_gen: "Generate",
    nav_export: "Export",
    nav_history: "History",
    nav_social: "Social Kit",
    nav_video: "Video (Veo)",
    nav_youtube: "YouTube Thumbnails",
    nav_projects: "Projects",
    nav_clients: "Clients",
    nav_ai_gallery: "AI Gallery",
    nav_ai_command: "AI Command Center",

    pipeline_workflow: "Workflow",
    pipeline_creative: "Creative",
    pipeline_management: "Management",
    pipeline_step_import: "Import",
    pipeline_step_culling: "Culling",
    pipeline_step_edit: "Base",
    pipeline_step_retouch: "Retouch",
    pipeline_step_export: "Export",

    status_draft: "New",
    status_editing: "Editing",
    status_review: "Review",
    status_delivered: "Delivered",

    crm_projects_title: "Projects",
    crm_projects_desc: "Overview of all jobs, statuses, and galleries.",
    crm_clients_title: "Clients",
    crm_clients_desc: "Manage contacts and their projects.",
    crm_filter_all: "All",
    crm_no_projects: "No projects yet.",
    crm_no_clients: "No clients yet.",
    crm_project_missing: "Project not found.",
    crm_client_missing: "Client not found.",
    crm_unknown_client: "Unknown client",
    crm_project_date: "Date",
    crm_files: "Files",
    crm_projects: "projects",
    crm_open_project: "Open project",
    crm_open_client: "Open client",
    crm_new_project: "New project",
    crm_new_project_desc: "Create a new job and pipeline.",
    crm_create_project: "Create project",
    crm_project_name: "Project name",
    crm_project_name_placeholder: "e.g. Novak Wedding",
    crm_project_type: "Job type",
    crm_notes: "Notes",
    crm_notes_placeholder: "Add notes for the job",
    crm_cancel: "Cancel",
    crm_client: "Client",
    crm_select_client: "Select client",
    crm_new_client_short: "+ New client",
    crm_new_client: "New client",
    crm_new_client_desc: "Create a client for fast assignments.",
    crm_create_client: "Create client",
    crm_client_name: "Client name",
    crm_client_name_placeholder: "e.g. John Novak",
    crm_email: "Email",
    crm_phone: "Phone",
    crm_activity_created: "Project created",
    crm_no_activity: "No activity yet.",
    crm_gallery_settings: "Gallery settings",
    crm_gallery_settings_desc: "Choose photos and access settings.",
    crm_publish: "Publish",
    crm_unpublish: "Unpublish",
    crm_selected: "Selected",
    crm_select_all: "Select all",
    crm_clear_selection: "Clear selection",
    crm_select: "Select",
    crm_allow_download: "Allow downloads",
    crm_upload_to_project: "Upload photos",
    crm_uploading_to: "Uploading to",
    crm_open_gallery: "Open gallery",
    crm_tab_info: "Info",
    crm_tab_photos: "Photos",
    crm_tab_gallery: "Gallery",
    crm_tab_activity: "Activity",
    crm_status: "Status",
    crm_no_files: "No photos yet.",
    crm_open_in_editor: "Open in editor",
    crm_gallery_missing: "Gallery not found.",
    crm_gallery_title: "Private gallery for client",
    crm_download_all: "Download all",
    crm_gallery_empty: "Gallery is empty.",

    dashboard_new_job: "New Job",
    dashboard_continue: "Continue Editing",
    dashboard_recent: "Recent Actions",
    dashboard_no_recent: "No history yet.",
    dashboard_quick_autopilot: "Quick Autopilot",
    dashboard_quick_culling: "Chytrý výběr",

    ai_gallery_search: "Search gallery...",
    ai_gallery_filter_all: "All",
    ai_gallery_filter_generate: "Generated",
    ai_gallery_filter_autopilot: "Autopilot",
    ai_gallery_filter_youtube: "YouTube thumbnails",
    ai_gallery_loading: "Loading gallery...",
    ai_gallery_empty: "No AI creations yet.",
    ai_gallery_download: "Download",
    ai_gallery_delete: "Delete",
    ai_gallery_select_project: "Select project",
    ai_gallery_add_to_project: "Add to project",

    template_title: "Choose Job Type",
    template_desc: "This optimizes AI models and pipeline for your specific workload.",
    template_portrait: "Portrait",
    template_portrait_desc: "Focus on skin tones and natural colors.",
    template_event: "Wedding / Event",
    template_event_desc: "Consistency and emotion for large volumes.",
    template_product: "Product",
    template_product_desc: "Sharp details and clean backgrounds.",
    template_social: "Social Media",
    template_social_desc: "Fast crops and viral captions.",
    template_skip: "Skip setup",

    credits_remaining: "Credits",
    credits_low: "Not enough credits",
    credits_cost: "Cost",
    credits_buy: "Buy Credits",
    
    store_title: "Credit Store",
    store_desc: "Unlock premium AI features. Credits are only deducted for successful generations.",
    store_pack_basic: "Starter",
    store_pack_pro: "Creator",
    store_pack_ultra: "Professional",
    store_btn_buy: "Purchase",
    store_best_value: "Best Value",
    store_success: "Credits added successfully!",
    
    onboarding_title: "Welcome to the Studio of the Future",
    onboarding_step1_title: "All in One Place",
    onboarding_step1_desc: "From RAW conversion to YouTube thumbnail generation. Photographer AI is your complete creative team.",
    onboarding_step2_title: "AI Works For You",
    onboarding_step2_desc: "Use 'Autopilot' for instant enhancement, or 'Smart Culling' to sort through hundreds of photos.",
    onboarding_step3_title: "Credit Economy",
    onboarding_step3_desc: "You start with 50 free credits. Demanding AI features (Generation, Veo) consume credits.",
    onboarding_btn_next: "Next",
    onboarding_btn_start: "Start Creating",

    turbo_culling: "Smart Culling",
    turbo_culling_desc: "AI analyzes quality and picks the best shots.",
    turbo_run_culling: "Run Quality Assessment",
    turbo_best_pick: "AI Favorite",
    turbo_bad_quality: "Warning: Poor Quality",
    turbo_express: "Turbo Workflow",
    turbo_express_desc: "One click: Autopilot + Crop + Social.",
    turbo_express_btn: "Run Turbo Workflow",
    
    home_title: "Fotograf AI",
    home_subtitle: "Professional workflow for photographers. Save time, create art, and get done in a flash.",
    home_enter: "Enter Studio",
    
    upload_title: "Upload Photos",
    upload_drag: "Drag & Drop photos here",
    upload_support: "Supports JPG, PNG, WEBP and",
    upload_raw: "RAW files will be automatically converted.",
    upload_btn: "Select Files",
    upload_processing: "Processing files...",
    
    editor_no_image: "No image selected",
    editor_upload_hint: "Upload an image to start editing.",
    editor_analyzing: "Analyzing...",
    editor_desc: "Description",
    editor_suggestions: "Suggestions",
    editor_proactive: "Proactive Suggestions",
    editor_tech: "Technical Info",
    
    tool_autopilot_desc: "Let AI automatically enhance your image.",
    tool_autopilot_btn: "Run Autopilot",
    tool_remove_desc: "Describe object to remove.",
    tool_remove_placeholder: "e.g. 'blue car'",
    tool_remove_btn: "Remove",
    tool_crop_title: "Chytrý ořez",
    tool_crop_instr: "AI Instructions",
    tool_crop_placeholder: "e.g. 'Crop to the face'",
    tool_crop_format: "Target Format",
    tool_crop_btn_only: "Crop Only",
    tool_crop_btn_export: "Crop & Export",
    tool_bg_desc: "Describe new background.",
    tool_bg_placeholder: "e.g. 'tokyo street'",
    tool_bg_btn: "Replace Background",
    tool_style_desc: "Apply style of another image.",
    tool_style_select: "Select Style Image",
    tool_style_btn: "Apply Style",

    tool_social_title: "Social Media Kit",
    tool_social_desc: "AI captions and hashtags for Instagram.",
    tool_social_btn: "Generate Content",

    tool_video_title: "Animate Photo (Veo)",
    tool_video_desc: "Generate video from photo using Veo.",
    tool_video_prompt: "Describe motion",
    tool_video_btn: "Generate Video",

    tool_youtube_title: "YouTube Thumbnails",
    tool_youtube_desc: "Create high-contrast thumbnails.",
    tool_youtube_topic: "Video Topic",
    tool_youtube_topic_ph: "e.g. iPhone 16 Review",
    tool_youtube_text: "Thumbnail Text",
    tool_youtube_text_ph: "e.g. SHOCKING TRUTH",
    tool_youtube_face: "Use current photo as face",
    tool_youtube_btn: "Generate Thumbnail",
    
    manual_title: "Manual Edits",
    manual_reset: "Reset",
    manual_crop_active: "Manual Crop",
    manual_brightness: "Brightness",
    manual_contrast: "Contrast",
    manual_saturation: "Saturation",
    manual_vibrance: "Vibrance",
    manual_shadows: "Shadows",
    manual_highlights: "Highlights",
    manual_clarity: "Clarity",
    manual_sharpness: "Sharpness",
    manual_noise: "Noise Reduction",
    manual_export_settings: "Export Settings",
    manual_finish: "Finish & Export",

    export_title: "Export Image",
    export_format: "Format",
    export_quality: "Quality",
    export_size: "Size",
    export_original: "Original",
    export_half: "Half",
    export_download: "Download",

    batch_title: "Batch Processing",
    batch_subtitle: "Apply AI to multiple images.",
    batch_select: "Select Images",
    batch_selected: "selected",
    batch_select_all: "Select All",
    batch_deselect_all: "Deselect All",
    batch_run: "Run Autopilot",
    batch_processing: "Processing...",
    batch_error: "Error processing",
    batch_complete: "Batch complete.",

    gen_title: "Create with AI",
    gen_subtitle: "Describe and create.",
    gen_prompt: "Prompt",
    gen_placeholder: "e.g. Astronaut on Mars",
    gen_btn: "Generate",
    gen_generating: "Generating...",
    gen_add: "Add to Project",
    
    raw_title: "RAW Converter",
    raw_subtitle: "Bulk RAW to JPEG conversion.",
    raw_convert: "Convert",
    raw_converting: "Converting...",
    raw_add: "Add to Studio",
    raw_convert_more: "Convert More",
    raw_done: "Done",
    raw_drag: "Drag RAW files here",
    raw_or_click: "or click",
    raw_select_other: "Select Other",
    raw_no_files: "No files selected.",
    
    msg_api_missing: "Communication error with AI service.",
    msg_success: "Success.",
    msg_error: "Error.",
    notify_upload_success: "files uploaded.",
    notify_gen_success: "Image generated.",
    notify_raw_success: "files prepared.",

    compare_before: "Before",
    compare_after: "After",
    compare_btn: "Compare",
    export_btn: "Export"
  }
};

type Translations = typeof translations.cs;

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: Translations;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('cs');
  return (
    <LanguageContext.Provider value={{ language, setLanguage, t: translations[language] }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useTranslation = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useTranslation must be used within a LanguageProvider');
  return context;
};
